#!/bin/zsh

NOTEFILE="~/notes/note-$(date +%Y-%m-%d).md"

if [[ ! -f $NOTEFILE ]]; then
  echo "# Notes for $(date +%Y-%m-%d)" > $NOTEFILE
fi

nvim -c "norm Go" \
  -c "norm Go ## $(date +%Y-%m-%d)" \
  -c "norm G2o" \
  -c "norm zz" \
  -c "startinsert" $NOTEFILE
